# Generated by Django 4.1.2 on 2022-11-01 12:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_offer', to='account_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_info', models.TextField()),
                ('cargo_type', models.CharField(blank=True, max_length=50, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('max_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('cargo_weight', models.IntegerField()),
                ('starting_location', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location_type', models.CharField(blank=True, choices=[('1', 'Country To Country'), ('2', 'City To City'), ('3', 'Inside City')], default='1', max_length=1, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_service', to='account_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, choices=[('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('awaiting_delivery', 'بانتظار التسليم'), ('complete', 'مكتمل'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض')], default='accepted', max_length=25, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('arrival_dt', models.DateTimeField(auto_now=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_order', to='services_app.offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='services_app.service', unique=True),
        ),
    ]
