# Generated by Django 4.1.2 on 2022-10-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
    ]
