# Generated by Django 4.1.2 on 2022-11-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='services_app.service'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('driver', 'service')},
        ),
    ]
