# Generated by Django 4.1.2 on 2022-11-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_alter_offer_service_alter_offer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_order', to='services_app.offer', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('accepted', 'مقبول'), ('in_progress', 'قيد التنفيذ'), ('awaiting_delivery', 'بانتظار التسليم'), ('complete', 'مكتمل'), ('cancelled', 'ملغي'), ('rejected', 'مرفوض')], default='accepted', max_length=25),
        ),
    ]
