# Generated by Django 4.1.2 on 2022-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'User'), ('2', 'Driver'), ('3', 'Customer')], default='1', max_length=1, null=True),
        ),
    ]
